### PR TITLE
Language-specific support framework + Dired support

### LINKED ISSUE #43: Turning on citre-mode in dired-mode
u-ctags can record included C header files as reference tags to a tags file 
If we can use citre-mode in dired-mode buffers, we can list "which source files includes foo.h" with pressing M-. on "foo.h", a dried entry.

### PR DESCRIPTION
**Pull request by AmaiKinono**
Close #43.

@masatake Could you try this out and see if there's any problem? I've tested it in some C projects but not sure if it's good enough.

### CODE REVIEW

**Comment by masatake** [comment]
About dired-mode, it works fine. Thank you.

About language mode, how do you think about `*-mode-local-*` functions avaiable when you load `mode-local.el` instead of having citre own `language -> functions` mapping? (This is my original plan that I wanted to implement.)

**Comment by AmaiKinono** [comment]
> how do you think about `*-mode-local-*` functions avaiable when you load `mode-local.el` instead of having citre own language -> functions mapping?

Thanks. I didn't know this before, looks very promising. But I'm having some troubles testing it out:

``` elisp
(require 'mode-local)
(defvar-mode-local emacs-lisp-mode test "elisp")
(defvar-mode-local dired-mode test "dired")
```

Now in a `*scratch*` buffer, type `M-x emacs-lisp-mode` and eval `test`, an error says its value is void.

Also, in a dired buffer, the same error occurs.

But if I open some file and change its major mode to `emacs-lisp-mode` or `dired-mode`, this works. I suspect this mechanism doesn't work well with non-file buffers.

**Comment by masatake** [comment]
It seems that the restriction comes from `mode-local-map-file-buffers`.
I wonder whether the restriction is essential part of the library.

**Comment by AmaiKinono** [comment]
Anyway, use major modes rather than language names in the `language -> functions` mapping is better, since it's not always reliable to guess the language based on the file name extension.

For now let's use a lookup table. Migrating to mode-local variables can be a future topic.

**Comment by AmaiKinono** [comment]
I changed the name of the "language" from `dired` to `fileref`, since there are also some other file browsers in Emacs (though I don't use them) and people may want to support them too.

**Comment by masatake** [comment]
Interesting. I would like to see ctire-lang-python.

**Comment by AmaiKinono** [comment]
Python is complicated. I plan to support C first.

**Pull request merged**
