### PR TITLE
Overhaul the test cases

### PR DESCRIPTION
**Pull request by masatake**

### CODE REVIEW

**Comment by masatake** [comment]
@AmaiKinono, is there a simple way to specify loading all fields int citre-get-records ?

**Comment by AmaiKinono** [comment]
Ah, I finished this task before I saw your PR ;)

> @AmaiKinono, is there a simple way to specify loading all fields in `citre-get-records`?

Yes. Use the keyword argument `:parse-all-fields`.

**Comment by masatake** [comment]
Thank you!

**Comment by AmaiKinono** [comment]
I should thank you ;)

**Pull request closed without merging**
